Fix README example for core/build-http-client and core/build-async-cttp-client
Pass empty sequence in place of false for the proxy-ignore-hosts parameter.  Passing false causes:

java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.lang.Boolean

from under clj-http.core/get-route-planner.